services:
  identityhub-provider:
    image: identity-hub-provider:latest  # Add explicit image name
    build:
      context: ..
      dockerfile: launchers/identity-hub/Dockerfile
    environment:
      LOG_LEVEL: debug
      IDENTITY_HUB_ROLE: provider
    volumes:
      - ./assets:/app/deployment/assets:ro
    network_mode: host
    restart: unless-stopped

  provider-catalog-server:
    build:
      context: ..
      dockerfile: launchers/catalog-server/Dockerfile
    environment:
      LOG_LEVEL: debug
    volumes:
      - ./assets:/app/deployment/assets:ro
    network_mode: host
    restart: unless-stopped
    depends_on:
      - identityhub-provider

  provider-connector-qna:
    build:
      context: ..
      dockerfile: launchers/runtime-embedded/Dockerfile
    environment:
      LOG_LEVEL: debug
    volumes:
      - ./assets:/app/deployment/assets:ro
    network_mode: host
    restart: unless-stopped
    depends_on:
      - identityhub-provider
      - provider-catalog-server

  provider-connector-manufacturing:
    build:
      context: ..
      dockerfile: launchers/runtime-embedded/Dockerfile
    environment:
      LOG_LEVEL: debug
    volumes:
      - ./assets:/app/deployment/assets:ro
    network_mode: host
    restart: unless-stopped
    depends_on:
      - identityhub-provider
      - provider-catalog-server
