services:
  identityhub-consumer:
    image: identity-hub-provider:latest  # Add explicit image name
    build:
      context: ..
      dockerfile: launchers/identity-hub/Dockerfile
    environment:
      LOG_LEVEL: debug
      IDENTITY_HUB_ROLE: consumer
    volumes:
      - ./assets:/app/deployment/assets:ro
    network_mode: host
    restart: unless-stopped

  consumer-connector:
    build:
      context: ..
      dockerfile: launchers/runtime-embedded/Dockerfile
    environment:
      LOG_LEVEL: debug
    volumes:
      - ./assets:/app/deployment/assets:ro
    network_mode: host
    restart: unless-stopped
    depends_on:
      - identityhub-consumer
