services:
  identityhub-consumer:
    build:
      context: ..
      dockerfile: launchers/identity-hub/Dockerfile
    env_file:
      - ./assets/env/consumer_identityhub.env
    environment:
      LOG_LEVEL: debug
      IDENTITY_HUB_ROLE: consumer
    volumes:
      - ./assets:/app/deployment/assets:ro
    network_mode: host
    restart: unless-stopped

  identityhub-provider:
    build:
      context: ..
      dockerfile: launchers/identity-hub/Dockerfile
    env_file:
      - ./assets/env/provider_identityhub.env
    environment:
      LOG_LEVEL: debug
      IDENTITY_HUB_ROLE: provider
    volumes:
      - ./assets:/app/deployment/assets:ro
    network_mode: host
    restart: unless-stopped

  issuer-service:
    build:
      context: ..
      dockerfile: launchers/issuerservice/Dockerfile
    env_file:
      - ./assets/env/issuerservice.env
    environment:
      LOG_LEVEL: debug
    volumes:
      - ./assets:/app/deployment/assets:ro
    network_mode: host
    restart: unless-stopped
    depends_on:
      - identityhub-consumer

  provider-catalog-server:
    build:
      context: ..
      dockerfile: launchers/catalog-server/Dockerfile
    env_file:
      - ./assets/env/provider_catalogserver.env
    environment:
      LOG_LEVEL: debug
    volumes:
      - ./assets:/app/deployment/assets:ro
    network_mode: host
    restart: unless-stopped
    depends_on:
      - identityhub-provider

  provider-connector-qna:
    build:
      context: ..
      dockerfile: launchers/runtime-embedded/Dockerfile
    env_file:
      - ./assets/env/provider_connector_qna.env
    environment:
      LOG_LEVEL: debug
      CONNECTOR_ROLE: provider-qna
    volumes:
      - ./assets:/app/deployment/assets:ro
    network_mode: host
    restart: unless-stopped
    depends_on:
      - identityhub-provider
      - provider-catalog-server

  provider-connector-manufacturing:
    build:
      context: ..
      dockerfile: launchers/runtime-embedded/Dockerfile
    env_file:
      - ./assets/env/provider_connector_manufacturing.env
    environment:
      LOG_LEVEL: debug
      CONNECTOR_ROLE: provider-manufacturing
    volumes:
      - ./assets:/app/deployment/assets:ro
    network_mode: host
    restart: unless-stopped
    depends_on:
      - identityhub-provider
      - provider-catalog-server

  consumer-connector:
    build:
      context: ..
      dockerfile: launchers/runtime-embedded/Dockerfile
    env_file:
      - ./assets/env/consumer_connector.env
    environment:
      LOG_LEVEL: debug
      CONNECTOR_ROLE: consumer
    volumes:
      - ./assets:/app/deployment/assets:ro
    network_mode: host
    restart: unless-stopped
    depends_on:
      - identityhub-consumer