# =========================
# Basic Broker Configuration
# =========================

persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

# =========================
# Listener
# =========================

listener 1883
allow_anonymous false

# =========================
# Dynamic Security Plugin
# =========================

plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/config/dynamic-security.json